stages:
  - sync

sync_to_github:
  stage: sync
  script:
    - git remote remove github || true
    - git remote add github https://$CI_PROJECT_NAMESPACE:$GITHUB_TOKEN@github.com/empty-labs/wordle-solver.git
    - git fetch github main
    - git rebase github/main
    - git push --force github HEAD:$CI_COMMIT_REF_NAME
    - git push --force github --tags
  only:
    - main
