stages:
  - sync

sync_to_github:
  stage: sync
  before_script:
    - git config --global core.compression 0
    - git repack -a -d --depth=250 --window=250
  script:
    - git remote remove github || true
    - git remote add github https://$CI_PROJECT_NAMESPACE:$GITHUB_TOKEN@github.com/empty-labs/wordle-solver.git
    - git fetch github || true
    - git push github +HEAD:main
    - git push github --tags
  only:
    - main