stages:
  - sync

sync_to_github:
  stage: sync
  script:
    - git remote remove github || true
    - git remote add github https://$CI_PROJECT_NAMESPACE:$GITHUB_TOKEN@github.com/empty-labs/wordle-solver.git
    - git fetch github
    - git push github +HEAD:main  # the '+' forces push (non-fast-forward allowed)
    - git push github --tags
  only:
    - main