stages:
  - sync

sync_to_github:
  stage: sync
  script:
    - git config user.name "GitLab CI"
    - git config user.email "ci@example.com"
    - git remote remove github || true
    - git remote add github https://$CI_PROJECT_NAMESPACE:$GITHUB_TOKEN@github.com/empty-labs/wordle-solver.git
    - git fetch github main
    - |
      git rebase github/main || {
        echo "🔀 Starting manual conflict resolution..."
        git diff --name-only --diff-filter=U | while read file; do
          echo "📄 Resolving conflict in $file by preferring ours"
          git checkout --ours "$file" || true
          git add "$file"
        done
        # Only commit if there are staged changes
        if ! git diff --cached --quiet; then
          git commit -m "Resolve merge conflicts during GitLab to GitHub sync"
        else
          echo "✅ No commit needed after conflict resolution"
        fi
        git rebase --continue || echo "⚠️ Rebase still failed. Manual fix may be required."
      }
    - git push github HEAD:main --force
    - git push github --tags --force
  only:
    - main